# Generated by Django 3.2.6 on 2021-08-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
